Fix error when navigating to cart page without localStorage['cart'] variable
NextCafeteria/cafeteria pull request #14
Opened 2023-05-26 08:10 UTC by sonthb3992

This pull request addresses an issue where navigating to the cart page without the localStorage['cart'] variable present causes an error. The error occurs because the code attempts to read the items from the localStorage['cart'], which is null when the variable is missing.
This pull request aims to improve the user experience by preventing potential errors when navigating to the cart page without the localStorage['cart'] variable. The fix ensures a smooth transition to the cart page even when the variable is missing.
Please review the changes and merge this pull request if it is deemed satisfactory.

2023-05-26 13:26 UTC, vietanhdev requested changes
Hi, @sonthb3992 !
Thank you for your contribution. Please update some points before I can merge your code.
Looking to your feedback.

2023-05-26 13:26 UTC, vietanhdev commented on src/lib/price.js
> +  if (items=== null) return 0;
Please add a space before `===`.
```
if (items=== null) return 0;
```

This repository uses `prettier` for code formatting. Please run the following command before committing to format your code automatically:

```
npm run pr
```

2023-05-26 13:26 UTC, vietanhdev commented on README.md
> +10. Click on the "Create" button to generate your credentials (ex: https://cafe.vietanh.dev/api/auth/callback/google).
`https://cafe.vietanh.dev/api/auth/callback/google` is a callback URL. It should be related to Step 9 instead of step 10.

2023-05-26 13:26 UTC, vietanhdev commented on README.md
> +1. Go to the Google Cloud Platform Console: https://console.cloud.google.com/
Please format your links in markdown format. For example:
```
[https://console.cloud.google.com/](https://console.cloud.google.com/)
```
Or
```
<https://console.cloud.google.com/>
```

2023-05-26 13:26 UTC, vietanhdev commented on README.md
> +11. On the Credentials page, locate your newly created OAuth 2.0 client ID and click on the download icon to the right of it. This will download a JSON file containing your credentials.
For this application, we prefer not to download this file. Instead, copy 2 values:
- Client ID. For example: `6989....c0tukv3fnhm.apps.googleusercontent.com`.
- Client secret. For example: `GOC......hgyO`.

**For local development, put these values inside .env file:**
```
NEXT_PUBLIC_GOOGLE_LOGIN="true"
GOOGLE_ID=6989....c0tukv3fnhm.apps.googleusercontent.com
GOOGLE_SECRET=GOC......hgyO
```

For Vercel cloud, put those values in the [Environment Variables](https://vercel.com/docs/concepts/projects/environment-variables).

2023-05-26 13:28 UTC, vietanhdev requested changes

2023-05-26 13:28 UTC, vietanhdev commented on README.md
>  - Add all environment variables to the project (see [.env.sample](.env.sample)).
We prefer to use `.env` file for local development. It contains other settings too. Therefore, please don't remove this instruction for `.env.sample`.

2023-05-27 02:39 UTC, sonthb3992 commented on src/lib/price.js
> +  if (items=== null) return 0;
Thanks. I'll use `prettier` for my repos too.

2023-05-27 02:45 UTC, sonthb3992 commented on README.md
> +10. Click on the "Create" button to generate your credentials (ex: https://cafe.vietanh.dev/api/auth/callback/google).
Will edit it

2023-05-27 02:46 UTC, sonthb3992 commented on README.md
> +1. Go to the Google Cloud Platform Console: https://console.cloud.google.com/
Will do

2023-05-27 02:46 UTC, sonthb3992 commented on README.md
> +11. On the Credentials page, locate your newly created OAuth 2.0 client ID and click on the download icon to the right of it. This will download a JSON file containing your credentials.
Updated the instruction

2023-05-27 03:07 UTC, vietanhdev commented on README.md
>  - Add all environment variables to the project (see [.env.sample](.env.sample)).
Please restore the instruction for `.env.sample` as it contains other variables too.

```
NEXT_PUBLIC_SERVER_URL=https://example.com
NEXTAUTH_URL=https://example.com
NEXTAUTH_SECRET=your-nextauth-secret

FIREBASE_API_KEY=your-firebase-api-key
FIREBASE_APP_ID=your-firebase-app-id
FIREBASE_AUTH_DOMAIN=your-firebase-auth-domain
FIREBASE_DATABASE_URL=your-firebase-database-url
FIREBASE_PROJECT_ID=your-firebase-project-id
FIREBASE_STORAGE_BUCKET=your-firebase-storage-bucket
FIREBASE_MESSAGING_SENDER_ID=your-firebase-messaging-sender-id

NEXT_PUBLIC_GOOGLE_LOGIN="true"
GOOGLE_ID=your-google-id
GOOGLE_SECRET=your-google-secret

NEXT_PUBLIC_GITHUB_LOGIN="true"
GITHUB_CLIENT_ID=your-github-client-id
GITHUB_CLIENT_SECRET=your-github-client-secret
```

2023-06-18 17:15 UTC, vietanhdev approved these changes

2023-06-18 17:16 UTC, merged