Update UI
NextCafeteria/cafeteria pull request #39
Opened 2023-07-07 17:30 UTC by perplexingcode

2023-07-07 17:42 UTC, vietanhdev requested changes
Run the following command to format the code before committing.
(We will setup this into git hook later).
```
npm run pr
```

2023-07-07 17:42 UTC, vietanhdev commented on src/app/[lng]/cart/page.js
> +      {cartData?.items?.length != 0 && (
Adding `{cartData && ` will help to hide the button when the cart is empty.

2023-07-07 17:42 UTC, vietanhdev commented on src/app/[lng]/products/page.js
> +<<<<<<< HEAD
Fix code merging. Please build before committing:
```
npm run build
```

2023-07-07 17:42 UTC, vietanhdev commented on src/app/[lng]/stores/page.js
> +<<<<<<< HEAD
Fix code merging

2023-07-07 17:45 UTC, vietanhdev commented
There are some changes that need to be added:
- Fix the product skeletons (too small now).
- Improve responsiveness.
![image](https://github.com/NextCafeteria/cafeteria/assets/18329471/8120a771-b639-4f65-b469-1a7f14eca80d)

2023-07-11 05:53 UTC, haitt00 approved these changes

2023-07-11 06:03 UTC, haitt00 reviewed
<img width="1039" alt="Screenshot 2023-07-11 at 13 01 48" src="https://github.com/NextCafeteria/cafeteria/assets/54594085/d8167954-f81b-4a9f-9ef3-0401d7af4d22">
@perplexingcode Button lưu thay đổi: boundary needs fixing.

Please resolve requested changes when done 👯

2023-07-11 15:54 UTC, haitt00 approved these changes

2023-07-11 15:55 UTC, merged